# A sample Gemfile
source "https://rubygems.org"
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-static-assets'
gem 'pg'
gem 'sinatra-sequel'
gem 'sinatra-respond_to'
gem 'httparty'
gem 'fileutils'
gem 'awesome_print'
gem 'thin'
gem 'nokogiri'
gem 'sax-machine'
gem 'json'
gem 'haml'
gem 'capistrano'
gem 'tire', '~>0.5.4'
gem 'log4r'
gem 'foreman'
gem 'resque', '~>1.1'
gem 'resque-status'
gem 'rbc'
gem 'roo'
gem 'logger'
gem 'chronic'
# gem "rails"
